/**
 * Autostart command - daemon 开机自启管理
 * Windows: HKCU Run 注册表键 + ~/.mcpdog 下隐藏 VBS 启动器
 * macOS: LaunchAgent (~/Library/LaunchAgents/com.mcpdog.daemon.plist)
 * Linux: systemd user unit (~/.config/systemd/user/mcpdog.service)
 */
import { CLIUtils } from '../cli-utils.js';
import { promises as fs, realpathSync } from 'fs';
import { exec } from 'child_process';
import { promisify } from 'util';
import os from 'os';
import path from 'path';

const execAsync = promisify(exec);

// 注册位置常量：Windows HKCU Run 键 + VBS；macOS LaunchAgent；Linux systemd user unit
const WIN_RUN_KEY = 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run';
const AUTOSTART_NAME = 'MCPDogDaemon';
const PLIST_LABEL = 'com.mcpdog.daemon';

export interface DaemonStartCommand {
  nodePath: string;
  cliPath: string;
  fromNpxCache: boolean;
}

// 从当前进程解析启动命令：node 绝对路径 + cli-main.js 绝对路径（不依赖 PATH）
// node 路径经 realpath 解析：fnm/nvm 等版本管理器返回会话级临时符号链接（如 fnm_multishells），重启后失效
export function buildDaemonStartCommand(): DaemonStartCommand {
  let nodePath = process.execPath;
  try {
    nodePath = realpathSync(process.execPath);
  } catch {
    // 解析失败沿用原路径
  }
  const cliPath = process.argv[1] || '';
  return { nodePath, cliPath, fromNpxCache: cliPath.includes('_npx') };
}

// vbs 字符串内双引号写作 ""；WScript.Shell.Run 直接 CreateProcess（不经 cmd），窗口样式 0 = 隐藏
// 注意保持纯 ASCII：wscript 按系统 ANSI 代码页解析 .vbs，非 ASCII 注释有编码风险
export function buildWindowsVbs(nodePath: string, cliPath: string): string {
  return `' MCPDog daemon autostart (generated by: mcpdog daemon autostart --enable)\n`
    + `' Check: mcpdog daemon status | Remove: mcpdog daemon autostart --disable\n`
    + `CreateObject("WScript.Shell").Run """${nodePath}"" ""${cliPath}"" daemon start --no-color", 0, False\n`;
}

export function buildLaunchAgentPlist(nodePath: string, cliPath: string, logFile: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.mcpdog.daemon</string>
  <key>ProgramArguments</key>
  <array>
    <string>${nodePath}</string>
    <string>${cliPath}</string>
    <string>daemon</string>
    <string>start</string>
    <string>--no-color</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${logFile}</string>
  <key>StandardErrorPath</key>
  <string>${logFile}</string>
</dict>
</plist>
`;
}

export function buildSystemdUnit(nodePath: string, cliPath: string): string {
  return `[Unit]
Description=MCPDog daemon
After=network.target

[Service]
ExecStart="${nodePath}" "${cliPath}" daemon start --no-color
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
`;
}

export class AutostartCommand {
  async execute(args: string[], options: Record<string, any>): Promise<void> {
    if (options.help) {
      this.showHelp();
      return;
    }
    if (options.enable) {
      await this.enable();
    } else if (options.disable) {
      await this.disable();
    } else {
      await this.status();
    }
  }

  private vbsPath(): string {
    return path.join(os.homedir(), '.mcpdog', 'mcpdog-autostart.vbs');
  }

  private plistPath(): string {
    return path.join(os.homedir(), 'Library', 'LaunchAgents', `${PLIST_LABEL}.plist`);
  }

  private unitPath(): string {
    return path.join(os.homedir(), '.config', 'systemd', 'user', 'mcpdog.service');
  }

  private warnIfNpx(): void {
    const { fromNpxCache } = buildDaemonStartCommand();
    if (fromNpxCache) {
      CLIUtils.warn('当前入口位于 npx 缓存目录，缓存清理/升级后自启可能失效；建议 npm i -g 全局安装后重新 --enable');
    }
  }

  private async enable(): Promise<void> {
    const { nodePath, cliPath } = buildDaemonStartCommand();
    if (!cliPath) {
      CLIUtils.error('无法确定 CLI 入口路径');
      process.exit(1);
    }
    this.warnIfNpx();

    if (process.platform === 'win32') {
      await fs.mkdir(path.dirname(this.vbsPath()), { recursive: true });
      await fs.writeFile(this.vbsPath(), buildWindowsVbs(nodePath, cliPath), 'utf-8');
      // /d 值本身含引号，需以 \" 转义传给 reg.exe（经 cmd shell 解析）
      await execAsync(`reg add "${WIN_RUN_KEY}" /v ${AUTOSTART_NAME} /t REG_SZ /d "wscript.exe \\"${this.vbsPath()}\\"" /f`);
      CLIUtils.success('已注册开机自启（当前用户登录时启动）');
      CLIUtils.info(`VBS: ${this.vbsPath()}`);
      CLIUtils.info(`Run 键: ${WIN_RUN_KEY} -> ${AUTOSTART_NAME}`);
    } else if (process.platform === 'darwin') {
      const logFile = path.join(os.homedir(), '.mcpdog', 'autostart.log');
      await fs.mkdir(path.dirname(this.plistPath()), { recursive: true });
      await fs.mkdir(path.dirname(logFile), { recursive: true });
      await fs.writeFile(this.plistPath(), buildLaunchAgentPlist(nodePath, cliPath, logFile), 'utf-8');
      // 先 unload 忽略未加载错误，再 load 使 RunAtLoad 生效
      await execAsync(`launchctl unload "${this.plistPath()}" 2>/dev/null; launchctl load "${this.plistPath()}"`);
      CLIUtils.success('已注册开机自启（LaunchAgent）');
      CLIUtils.info(`plist: ${this.plistPath()}`);
    } else {
      // Linux：enable 只注册不立即启动（--now 会与运行中 daemon 冲突报 failed）
      await fs.mkdir(path.dirname(this.unitPath()), { recursive: true });
      await fs.writeFile(this.unitPath(), buildSystemdUnit(nodePath, cliPath), 'utf-8');
      try {
        await execAsync('systemctl --user daemon-reload && systemctl --user enable mcpdog');
        CLIUtils.success('已注册开机自启（systemd user unit）');
        CLIUtils.info(`unit: ${this.unitPath()}`);
      } catch (error) {
        CLIUtils.error(`systemd user 不可用（${(error as Error).message}），请改用桌面环境自启机制手动配置`);
        process.exit(1);
      }
    }
  }

  private async disable(): Promise<void> {
    if (process.platform === 'win32') {
      try {
        await execAsync(`reg delete "${WIN_RUN_KEY}" /v ${AUTOSTART_NAME} /f`);
      } catch {
        // 键值不存在视为已清理
      }
      try {
        await fs.unlink(this.vbsPath());
      } catch {
        // 文件不存在则忽略
      }
      CLIUtils.success('已移除开机自启');
    } else if (process.platform === 'darwin') {
      try {
        await execAsync(`launchctl unload "${this.plistPath()}"`);
      } catch {
        // 未加载则忽略
      }
      try {
        await fs.unlink(this.plistPath());
      } catch {
        // 文件不存在则忽略
      }
      CLIUtils.success('已移除开机自启');
    } else {
      try {
        await execAsync('systemctl --user disable mcpdog');
      } catch {
        // 未注册则忽略
      }
      try {
        await fs.unlink(this.unitPath());
        await execAsync('systemctl --user daemon-reload');
      } catch {
        // 文件不存在则忽略
      }
      CLIUtils.success('已移除开机自启');
    }
  }

  private async status(): Promise<void> {
    if (process.platform === 'win32') {
      try {
        const { stdout } = await execAsync(`reg query "${WIN_RUN_KEY}" /v ${AUTOSTART_NAME}`);
        CLIUtils.success('开机自启：已启用');
        CLIUtils.info(stdout.trim());
      } catch {
        CLIUtils.info('开机自启：未启用（mcpdog daemon autostart --enable 开启）');
      }
    } else if (process.platform === 'darwin') {
      const exists = await fs.access(this.plistPath()).then(() => true).catch(() => false);
      CLIUtils.info(exists
        ? '开机自启：已启用（LaunchAgent 已安装）'
        : '开机自启：未启用（mcpdog daemon autostart --enable 开启）');
    } else {
      try {
        await execAsync('systemctl --user is-enabled mcpdog');
        CLIUtils.info('开机自启：已启用（systemd user unit）');
      } catch {
        CLIUtils.info('开机自启：未启用（mcpdog daemon autostart --enable 开启）');
      }
    }
  }

  private showHelp(): void {
    console.log(`
${CLIUtils.colorize('mcpdog daemon autostart', 'cyan')} - Manage daemon auto-start on login/boot

${CLIUtils.colorize('Usage:', 'yellow')}
  mcpdog daemon autostart --enable     Register auto-start for current user
  mcpdog daemon autostart --disable   Remove auto-start registration
  mcpdog daemon autostart             Show current registration status

${CLIUtils.colorize('Description:', 'yellow')}
  Windows:  HKCU Run registry key + hidden VBS launcher in ~/.mcpdog
  macOS:    LaunchAgent (~/Library/LaunchAgents/com.mcpdog.daemon.plist)
  Linux:    systemd user unit (~/.config/systemd/user/mcpdog.service)

  Note: if installed via npx, the registration points into the npx cache and
  may break after cache cleanup - prefer a global install (npm i -g).
`);
  }
}
