/**
 * Service Command - Register/unregister MCPDog daemon OS auto-start
 *
 * 让 daemon 的生命周期与 MCP 会话解耦：登录操作系统即启动 daemon（含 38881 dashboard），
 * 不再依赖 MCP 客户端新会话 spawn proxy 时自动拉起。
 *
 * 各平台实现：
 * - Windows: 启动文件夹中的 VBS（Wscript.Shell Run 隐藏窗口启动，避免常驻控制台）
 * - macOS:   LaunchAgent plist（RunAtLoad + KeepAlive）
 * - Linux:   systemd user unit（WantedBy=default.target）
 */

import { CLIUtils } from '../cli-utils.js';
import { ConfigManager } from '../../config/config-manager.js';
import { promises as fs } from 'fs';
import { existsSync } from 'fs';
import path from 'path';
import os from 'os';
import { exec } from 'child_process';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const WINDOWS_VBS_NAME = 'mcpdog-daemon.vbs';
const MACOS_PLIST_LABEL = 'com.keysqiu.mcpdog.daemon';
const LINUX_UNIT_NAME = 'mcpdog.service';

export class ServiceCommands {
  constructor(private configManager: ConfigManager) {}

  async execute(args: string[], _options: Record<string, any>): Promise<void> {
    const [subcommand] = args;

    if (!subcommand || subcommand === 'help') {
      this.showHelp();
      return;
    }

    switch (subcommand) {
      case 'install':
        await this.install();
        break;
      case 'uninstall':
        await this.uninstall();
        break;
      case 'status':
        await this.status();
        break;
      default:
        CLIUtils.error(`Unknown service command: ${subcommand}`);
        CLIUtils.info('Available commands: install, uninstall, status');
        process.exit(1);
    }
  }

  // ---------- 平台相关的纯内容构造（便于单元测试） ----------

  /** Windows VBS：隐藏窗口启动 daemon（Run 第 2 参数 0 = 隐藏） */
  static buildVbsScript(nodeExe: string, cliEntry: string, configPath: string): string {
    const cmd = `"${nodeExe}" "${cliEntry}" daemon start --config "${configPath}"`;
    return [
      `' MCPDog daemon auto-start (generated by: mcpdog service install)`,
      `CreateObject("Wscript.Shell").Run "${cmd.replace(/"/g, '""')}", 0, False`,
      ''
    ].join('\r\n');
  }

  /** macOS LaunchAgent plist */
  static buildPlistXml(nodeExe: string, cliEntry: string, configPath: string): string {
    return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${MACOS_PLIST_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${nodeExe}</string>
    <string>${cliEntry}</string>
    <string>daemon</string>
    <string>start</string>
    <string>--config</string>
    <string>${configPath}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${path.join(os.homedir(), '.mcpdog', 'daemon-autostart.log')}</string>
  <key>StandardErrorPath</key>
  <string>${path.join(os.homedir(), '.mcpdog', 'daemon-autostart.log')}</string>
</dict>
</plist>
`;
  }

  /** Linux systemd user unit */
  static buildSystemdUnit(nodeExe: string, cliEntry: string, configPath: string): string {
    return `[Unit]
Description=MCPDog Daemon
After=network.target

[Service]
ExecStart=${nodeExe} ${cliEntry} daemon start --config ${configPath}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
`;
  }

  // ---------- 路径解析 ----------

  /** 当前运行实例的 cli-main.js（编译后 dist/cli/commands → dist/cli/cli-main.js） */
  private getCliEntry(): string {
    return path.join(__dirname, '..', 'cli-main.js');
  }

  private getWindowsVbsPath(): string {
    const appData = process.env.APPDATA || path.join(os.homedir(), 'AppData', 'Roaming');
    return path.join(appData, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup', WINDOWS_VBS_NAME);
  }

  private getMacosPlistPath(): string {
    return path.join(os.homedir(), 'Library', 'LaunchAgents', `${MACOS_PLIST_LABEL}.plist`);
  }

  private getLinuxUnitPath(): string {
    return path.join(os.homedir(), '.config', 'systemd', 'user', LINUX_UNIT_NAME);
  }

  private getServiceFilePath(): string {
    switch (process.platform) {
      case 'win32': return this.getWindowsVbsPath();
      case 'darwin': return this.getMacosPlistPath();
      default: return this.getLinuxUnitPath();
    }
  }

  // ---------- 子命令 ----------

  private async install(): Promise<void> {
    const nodeExe = process.execPath;
    const cliEntry = this.getCliEntry();
    const configPath = this.configManager.getConfigPath();
    const serviceFile = this.getServiceFilePath();

    if (!existsSync(cliEntry)) {
      CLIUtils.error(`CLI entry not found: ${cliEntry}`);
      CLIUtils.info('Please run "mcpdog service install" from an installed mcpdog package.');
      process.exit(1);
    }

    // 确保目标目录存在（如 Windows 启动文件夹、macOS LaunchAgents）
    await fs.mkdir(path.dirname(serviceFile), { recursive: true });
    await fs.mkdir(path.join(os.homedir(), '.mcpdog'), { recursive: true });

    switch (process.platform) {
      case 'win32':
        await fs.writeFile(serviceFile, ServiceCommands.buildVbsScript(nodeExe, cliEntry, configPath));
        break;
      case 'darwin':
        await fs.writeFile(serviceFile, ServiceCommands.buildPlistXml(nodeExe, cliEntry, configPath));
        await this.tryExec('launchctl unload ' + quote(serviceFile));
        await this.tryExec('launchctl load ' + quote(serviceFile));
        break;
      default: {
        await fs.writeFile(serviceFile, ServiceCommands.buildSystemdUnit(nodeExe, cliEntry, configPath));
        await this.tryExec('systemctl --user daemon-reload');
        await this.tryExec(`systemctl --user enable --now ${LINUX_UNIT_NAME}`);
        break;
      }
    }

    CLIUtils.success(`MCPDog daemon auto-start installed: ${serviceFile}`);
    CLIUtils.info(`Daemon command: daemon start --config ${configPath}`);
    CLIUtils.info('The dashboard will be available at http://localhost:38881 after next login.');
  }

  private async uninstall(): Promise<void> {
    const serviceFile = this.getServiceFilePath();

    if (!existsSync(serviceFile)) {
      CLIUtils.warn('MCPDog daemon auto-start is not installed');
      return;
    }

    switch (process.platform) {
      case 'darwin':
        await this.tryExec('launchctl unload ' + quote(serviceFile));
        break;
      default:
        await this.tryExec(`systemctl --user disable --now ${LINUX_UNIT_NAME}`);
        break;
    }

    await fs.unlink(serviceFile);
    CLIUtils.success('MCPDog daemon auto-start uninstalled');
  }

  private async status(): Promise<void> {
    const serviceFile = this.getServiceFilePath();

    if (!existsSync(serviceFile)) {
      CLIUtils.warn('MCPDog daemon auto-start is not installed');
      CLIUtils.info('Run "mcpdog service install" to enable auto-start on login.');
      return;
    }

    CLIUtils.success('MCPDog daemon auto-start is installed');
    CLIUtils.info(`Service file: ${serviceFile}`);
  }

  // ---------- 工具 ----------

  /** best-effort 执行系统命令，失败只提示不中断 */
  private async tryExec(command: string): Promise<void> {
    await new Promise<void>((resolve) => {
      exec(command, (error) => {
        if (error) {
          CLIUtils.warn(`Command failed (can be run manually): ${command}`);
        }
        resolve();
      });
    });
  }

  private showHelp(): void {
    console.log(`
${CLIUtils.colorize('mcpdog service', 'cyan')} - Manage MCPDog daemon OS auto-start

${CLIUtils.colorize('Usage:', 'yellow')}
  mcpdog service <subcommand>

${CLIUtils.colorize('Subcommands:', 'yellow')}
  install                Register daemon to start on login (Windows VBS / macOS LaunchAgent / Linux systemd user unit)
  uninstall              Remove the auto-start registration
  status                 Show whether auto-start is installed

${CLIUtils.colorize('Description:', 'yellow')}
  Auto-start decouples the daemon (dashboard http://localhost:38881 + IPC port 9999)
  from MCP client sessions, so no new session is required after a reboot.
`);
  }
}

function quote(p: string): string {
  return process.platform === 'win32' ? `"${p}"` : `'${p}'`;
}
